name: Docs Update Bypass

on:
  pull_request:
    branches:
      - main
    # WAKE UP if only these files change
    paths:
      - '**.md'          
      - 'docs/**'
      - '.gitignore'

jobs:
  # to bypass all stages if only docs are updated
  
  quality-gates:
    name: "🧹 Quality & Syntax"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Docs only update. Bypassing Quality & Syntax."

  security-scans:
    name: "🔒 Security Audit"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Docs only update. Bypassing Security Audit."

  deploy:
    name: "🚀 Execute Deployment"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Docs only update. Bypassing Deployment."

